version: '3.8'

services:
  app:
    image: my-app
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app

  db:
    image: "mysql:8.0"
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dockerTestDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - '3307:3306'
    expose:
      - 3306
    networks:
      - app

networks:
  app:
